---
title: Manfranklin.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: false
  showcase:
    title: Showcase
    output: true
    permalink: "/showcase/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    language: en
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    language: en
    comments: false
    author: Manuel Franklin
    published: true
    permalink: "/blog/:year/:month/:day/:title/"
- scope:
    path: _showcase
    type: showcase
  values:
    layout: showcase
- scope:
    path: pt
  values:
    language: pt
- scope:
    path: en
  values:
    language: en
name: Manuel Franklin
author: Manuel Franklin
description: Personal website and portfolio of Manuel Franklin.
avatar: "/images/reverie.png"
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: manfranklin
  instagram: 
  linkedin: 
  pinterest: 
  rss: feed
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
  playconsole: 
  mastodon: 
disqus: 
google_analytics: 
url: https://manfranklin.github.io
baseurl: 
enforce_ssl: https://manfranklin.github.io
permalink: "/:title/"
umami_domain: cloud.umami.is
umami_enabled: true
UMAMI_CLIENT_ID: ''
default_language: en
languages:
  en:
    name: EN
    direction: ltr
  pt:
    name: PT-AO
    direction: ltr
build_languages:
- en
- pt
excerpt_separator: "<!--more-->"
pagination:
  enabled: true
  per_page: 6
  permalink: "/blog/page/:num/"
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: compressed
  load_paths:
  - _sass
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate-v2
- jekyll-redirect-from
- jekyll-relative-links
responsive_image:
  default_quality: 90
  sizes:
  - "(min-width: 1200px) 33vw"
  - "(min-width: 768px) 50vw"
  - 100vw
  output_path_format: assets/resized/%{dirname}/%{basename}-%{width}x%{height}.%{extension}
  template: _includes/responsive-image.html
include:
- _pages
- ".htaccess"
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
- ".DS_Store"
- node_modules
- ".git"
- ".gitignore"
- Makefile
- vendor/
- "*.code-workspace"
feed:
  path: feed.xml
  collections:
    posts:
      path: "/feed.xml"
keep_files:
- ".git"
- ".github"
- CNAME
future: false
highlighter: rouge
liquid:
  error_mode: strict
search:
  enabled: true
  pagefind:
    enabled: true
    index_path: "/pagefind"
